<!--formulaire d'ajout de destination-->
<section>
  <p>
    <a href="index.php?route=pannelDestinations" title="Liste des destinations"
      >retour</a
    >
  </p>
  <h1>Ajout d'une destination :</h1>
  <!--enctype='multipart/form-data' pour pouvoir envoyer un fichier à partir d'un form:-->
  <form
    action="index.php?route=submitAddDestinations"
    method="POST"
    enctype="multipart/form-data"
  >
    <!--PAYS-->
    <div>
      <label for="country">Pays<sup>*</sup></label>
      <input
        type="text"
        class="prevent_enter"
        name="country"
        placeholder="50 caractères max"
        required
      />
      <?php if( isset($_SESSION['formDestinationsErrors']['countryError']) ) : ?>
      <?php foreach( $_SESSION['formDestinationsErrors']['countryError'] as $errorMessage ) : ?>
      <span class="error_message">
        <?= $errorMessage ?>
      </span>
      <?php endforeach; ?>
      <?php endif; ?>
    </div>
    <!--VILLE-->
    <div>
      <label for="city">Ville<sup>*</sup></label>
      <input
        type="text"
        class="prevent_enter"
        name="city"
        placeholder="60 caractères max"
        required
      />
      <?php if( isset($_SESSION['formDestinationsErrors']['cityError']) ) : ?>
      <?php foreach( $_SESSION['formDestinationsErrors']['cityError'] as $errorMessage ) : ?>
      <span><?= $errorMessage ?></span>
      <?php endforeach; ?>
      <?php endif; ?>
    </div>
    <!--CONTINENT-->
    <div>
      <label for="world_area">Continent</label>
      <select name="world_area" required>
        <option>Europe</option>
        <option>Asie</option>
        <option>Amérique du Nord</option>
        <option>Amérique du Sud</option>
        <option>Afrique</option>
        <option>Océanie</option>
        <option>Antarctique</option>
        <option>Inconnu</option>
      </select>
      
      <?php if( isset($_SESSION['formDestinationsErrors']['world_areaError']) ) : ?>
      <?php foreach( $_SESSION['formDestinationsErrors']['world_areaError'] as $errorMessage ) : ?>
      <span class="error_message">
        <?= $errorMessage ?>
      </span>
      <?php endforeach; ?>
      <?php endif; ?>
    
    </div>
    <!--DESCRIPTION-->
    <div>
      <label for="description">Description<sup>*</sup></label>
      <textarea
        name="description"
        rows="10"
        cols="80"
        wrap="50"
        required
      >
      </textarea>
      
      <?php if( isset($_SESSION['formDestinationsErrors']['descriptionError']) ) : ?>
      <?php foreach( $_SESSION['formDestinationsErrors']['descriptionError'] as $errorMessage ) : ?>
      <span class="error_message">
        <?= $errorMessage ?>
      </span>
      <?php endforeach; ?>
      <?php endif; ?>
    
    </div>
    <!--IMAGE-->
    <div>
      <label for="file">
        Image illustrant la destination (2Mo max)<sup>*</sup>
      </label>
      <input type="file" 
             name="file" 
             accept=".jpg,.jpeg,.png"
      />
      
      <?php if( isset($_SESSION['formDestinationsErrors']['fileError']) ) : ?>
      <?php foreach( $_SESSION['formDestinationsErrors']['fileError'] as $errorMessage ) : ?>
      <span class="error_message">
        <?= $errorMessage ?>
      </span>
      <?php endforeach; ?>
      <?php endif; ?>
    
    </div>
    <!--pour le alt="" de l'image-->
    <div>
      <label for="caption"
        >Description claire et succincte de ce qui est visible à l'image<sup
          >*</sup
        ></label
      >
      <textarea
        name="caption"
        rows="5"
        cols="40"
        wrap="50"
        placeholder="120 caractères max et évitez les 'images de...' ou 'photo de'... "
        required
      >
      </textarea>
      
      <?php if( isset($_SESSION['formDestinationsErrors']['captionError']) ) : ?>
      <?php foreach( $_SESSION['formDestinationsErrors']['captionError'] as $errorMessage ) : ?>
      <span class="error_message">
        <?= $errorMessage ?>
      </span>
      <?php endforeach; ?>
      <?php endif; ?>
    
    </div>
    <!--statut de la destination pour style CSS:-->
    <div>
      <label for="status"
        >Statut de la destination lors de sa mise en ligne</label
      >
      <select name="status" required>
        <option>Nouveauté</option>
        <option>Normal</option>
        <option>Prochainement</option>
        <option>Bientôt retirée</option>
        <option>Top 1 départ</option>
        <option>Top 1 arrivée</option>
        <option>Indisponible</option>
      </select>
      
      <?php if( isset($_SESSION['formDestinationsErrors']['statusError']) ) : ?>
      <?php foreach( $_SESSION['formDestinationsErrors']['statusError'] as $errorMessage ) : ?>
      <span class="error_message">
        <?= $errorMessage ?>
      </span>
      <?php endforeach; ?>
      <?php endif; ?>
    
    </div>
    <!--pour rendre destinations indisponible + autre statut-->
    <div>
      <label for="is_available"
        >Réservations possible dès la mise en ligne (oui si cochée)</label
      >
      <input type="checkbox" name="is_available" checked />
    </div>
    <div>
      <button type="submit" name="validate">Valider</button>
    </div>
  </form>
</section>
