<!--pour supprimer destination-->
<section>
  <h1>
    Supprimer la destination
    <?= htmlspecialchars( $destinationValues['city'] ); ?>
    (<?= htmlspecialchars( $destinationValues['country'] ); ?>) ?
  </h1>
  <div>
    <form
      action="index.php?route=submitDeleteDestinations&destinationid=<?= htmlspecialchars( $destinationValues['id_destination'] ); ?>&pictureid=<?= htmlspecialchars( $pictureValues['id_picture'] ); ?>"
      method="POST"
    >
      <div>
        <label for="check_delete"
          >Veuillez cocher cette case avant de valider</label
        >
        <input type="checkbox" name="check_delete" required />
        <?php if( isset( $_SESSION['formDeleteDestinationError']['checkDeleteDestinationError'] ) ) : ?>
        <span class="error_message">
          <?= $_SESSION['formDeleteDestinationError']['checkDeleteDestinationError'] ?>
        </span>
        <?php endif; ?>
      </div>

      <div>
        <button type="submit">Valider</button>
      </div>
    </form>

    <p>
      <a href="index.php?route=pannelDestinations" title="Retour">Annuler</a>
    </p>
  </div>
</section>
