<!--section recherche destinations-->
<section class="pickDestination_container">
  <div class="pickDestination--overlay">
    <div class="pickDestination__description">
      <h1 class="pickDestination__title">Atteignez votre destination en un instant</h1>
      <p>Un large choix de villes à travers le monde</p>
    </div>
    <!--formulaire de selection d'une destination-->
    <div class="pickDestination__form">
      <form action="index.php?route=submitItineraryUsers" method="POST">
        <div>
          <label for="departure"
            >Ville de départ</label
          >
        </div>
        <select class="pickDestination__select" name="departure" id="departure" required>
          <option value=""></option>
          <?php foreach ($destinations as $destination) : ?>
          <option
            value="<?= htmlspecialchars($destination['id_destination']); ?>"
          >
            <?= htmlspecialchars($destination['city']); ?>
            (<?= htmlspecialchars($destination['country']); ?>)
          </option>
          <?php endforeach ?>
        </select>

        <div>
          <button
            class="pickDestination__btn--swap"
            id="swap_destinations"
            name="swap_destinations"
            type="button"
            title="Inverser les lieux de départ et d'arrivée"
          >
            <img class="pickDestination__btn--img" id="btnSwap_img" src="public/img/arrow-reverse.svg" alt="inverser" />
          </button>
        </div>

        <div>
          <label for="arrival">Ville d'arrivée</label>
        </div>
        <select class="pickDestination__select" name="arrival" id="arrival" required>
          <option value=""></option>
          <?php foreach ($destinations as $destination) : ?>
          <option
            value="<?= htmlspecialchars($destination['id_destination']); ?>"
          >
            <?= htmlspecialchars($destination['city']); ?>
            (<?= htmlspecialchars($destination['country']); ?>)
          </option>
          <?php endforeach ?>
        </select>

        <div>
          <button
            class="pickDestination__btn--submit"
            type="submit"
            title="Rechercher ce trajet"
          >
            Rechercher
          </button>
        </div>

        <?php if (isset($_SESSION['submitItineraryErrors'])) : ?>
        <span class="error_message">
          <?= $_SESSION['submitItineraryErrors'] ?>
        </span>
        <?php endif; ?>
      
      </form>
    </div>
  <!--fin du formulaire-->
    <div class="pickDestination__link_block">
      <a
        class="pickDestination__link"
        href="index.php?route=homeDestinations"
        title="Nos destinations"
      >
        Voir nos destinations</a
      >
    </div>
  </div>
</section>
<!--fin de section-->

<!--section services-->
<section class="home_services">
  <div class="home_services__title_block">
    <h2 class="home_services__title">Services</h2>
  </div>

  <article class="home_services__infos">
    <img src="public/img/icone-fast.svg" alt="" />
    <h3>Rapidité</h3>
    <p>Entre 2 et 10 minutes par trajets</p>
  </article>

  <article class="home_services__infos">
    <img src="public/img/icone-security.svg" alt="" />
    <h3>Sécurité</h3>
    <p>Chute impossible pendant le transport</p>
  </article>

  <article class="home_services__infos">
    <img src="public/img/icone-eco.svg" alt="" />
    <h3>Respect</h3>
    <p>Aucun impact sur les écosystèmes</p>
  </article>

  <article class="home_services__infos">
    <img src="public/img/icone-refund.svg" alt="" />
    <h3>Flexibilité</h3>
    <p>Billets annulables et remboursables</p>
  </article>
</section>
<!--fin de section-->
<p>
  <a
    class="home_services__link"
    href="index.php?route=homeServices"
    title="Services"
  >
    En savoir plus</a
  >
</p>