<!--affichage des services-->
<div>
    <ul>
        <li>
            <a href="index.php?route=home" title="Accueil">retour</a>
        </li>
    </ul>
</div>
<section>
    <h1>Nos services</h1>
    <article>
        <div>
            <div>
                <p>
                    <img src="public/img/calendar.svg" alt="">
                </p>
            </div>
            <h2>Réservations</h2>
            <div>
                <p>
                    Réserver un voyage et gérer sa réservation.
                </p>
            </div>
            <div>
                <p>
                    <a href="#to-booking-services" title="Détails réservations">
                        <img src="public/img/arrow-down.svg" 
                             alt="flèche bas"></a>
                </p>
            </div>
        </div>
    </article>
    <article>
        <div>
            <div>
                <p>
                    <img src="public/img/baggage.svg" alt="">
                </p>
            </div>
            <h2>Extras</h2>
            <div>
                <p>
                    Les bagages, animaux et accessoires autorisés à bord.
                </p>
            </div>
            <div>
                <p>
                    <a href="#to-baggage-services" title="Détails extras">
                        <img src="public/img/arrow-down.svg" 
                             alt="flèche bas"></a>
                </p>
            </div>
        </div>
    </article>
    <article>
        <div>
            <div>
                <p>
                    <img src="public/img/accessibility.svg" alt="">
                </p>
            </div>
            <h2>Accessibilité</h2>
            <div>
                <p>
                    Des infrastructures adaptées aux personnes à mobilité réduite.
                </p>
            </div>
            <div>
                <p>
                    <a href="#to-accessibility-services" title="Détails accessibilité">
                        <img src="public/img/arrow-down.svg" 
                             alt="flèche bas"></a>
                </p>
            </div>
        </div>
    </article>
    <article>
        <div>
            <div>
                <p>
                    <img src="public/img/infrastructures.svg" alt="">
                </p>
            </div>
            <h2>Infrastructures</h2>
            <div>
                <p>
                    Proximité de grands axes, transports et restauration.
                </p>
            </div>
            <div>
                <p>
                    <a href="#to-infrastructures-services" title="Détails infrastructures">
                        <img src="public/img/arrow-down.svg" 
                             alt="flèche bas"></a>
                </p>
            </div>
        </div>
    </article>
</section>

<section>
    <h2 id="to-booking-services" class="title_booking-services-logo">Réservations</h2>
    <article>
        <h3>Possibilités de réservations</h3>
        <p>
            Vous avez la possibilité de réserver en ligne sur notre site, sur notre application
            mobile ou bien dans l'un de nos points de vente présent dans les villes desservies par Worldlink.
        </p>
    </article>
    <article>
        <h3>Disponibilité complète</h3>
        <p>
            Pour vous permettre de partir n'importe quand, nos équipes se relaient pour vous offrir un
            service disponible 24h/24 et 7 jrs/7 !
        </p>
    </article>
    <article>
        <h3>Moyens de paiements</h3>
        <p>
            Un large choix de mode de paiement est diponible : Paypal, carte bancaire, virement ou encore
            en espèce ou par chèque dans nos points de vente.
        </p>
    </article>
    <article>
        <h3>Annulations et remboursement</h3>
        <p>
            Vous pouvez annuler votre réservation à tout moment et obtenir un remboursement complet si vous le 
            faites au plus tard 15 minutes avant le départ.
        </p>
    </article>
</section>

<section>
    <h2 id="to-baggage-services">Extras</h2>
    <article>
        <h3>Valises et sacs</h3>
        <p>
            Vous êtes autorisé à emporter un bagage à main et une valise avec vous.
            Des restrictions de tailles et de poids leur seront soumis.
        </p>
    </article>
    <article>
        <h3>Animaux</h3>
        <p>
            Les animaux sont autorisés à bord à condition qu'ils rentrent dans nos niches
            de transports conçues spécialement pour eux. Pour des raisons de sécurité elles sont obligatoires !
        </p>
    </article>
    <article>
        <h3>Autres accessoires</h3>
        <p>
            Les vélos, trottinettes et autres moyens de locomotion sont autorisés à la stricte condition qu'ils 
            puissent être portés à la main lors du voyage.
        </p>
    </article>
</section>

<section>
    <h2 id="to-accessibility-services">Accessibilité</h2>
    <article>
        <h3>Personnes en situation de handicap</h3>
        <p>
            L'accès à la zone d'ascension ainsi que les zones de confort aux abords sont entièrement aménagées pour
            les personnes à mobilité réduites !
        </p>
    </article>
    <article>
        <h3>Femmes enceintes</h3>
        <p>
            L'ascension pouvant être brusque, l'accès aux femmes enceintes est déconseillé.
        </p>
    </article>
</section>

<section>
    <h2 id="to-infrastructures-services">Infrastructures</h2>
    <article>
        <h3>Transports en commun</h3>
        <p>
            Pour faciliter vos déplacements au départ et à l'arrivée, les points d'ascensions sont proches des gares, aéroports
            et ports des villes desservies !
        </p>
    </article>
    <article>
        <h3>Restauration</h3>
        <p>
            Des restaurants sont présents aux abords du points d'ascensions.
        </p>
    </article>
</section>

<div>
    <p>D'autres questions ? Consultez notre
        <a href="index.php?route=notAvailable">Rubrique d'aides</a>
    </p>
</div>